name: electron-fittexxcoin
version: master
summary: Fittexxcoin thin client
description: |
  Lightweight Fittexxcoin client

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  electron-fittexxcoin:
    command: desktop-launch electron-fittexxcoin
    plugs: [network, network-bind, x11, unity7]

parts:
  electron-fittexxcoin:
    source: .
    plugin: python
    python-version: python3
    stage-packages: [python3-pyqt5]
    build-packages: [pyqt5-dev-tools]
    after: [desktop-qt5]
